#NAME: Omar Ahmad
#EMAIL: omarahmad4@ucla.edu
#ID: 804801272

CC = gcc
CFLAGS = -Wall -Wextra -g

default: source.c
	@$(CC)  $(CFLAGS) -o lab3b source.c

clean:
	@rm -f lab3b *.gz

dist:
	@tar -cvzf lab3b-804801272.tar.gz source.c Makefile README

check:
	-@./lab3b data/P3B-test_1.csv
	-@./lab3b data/P3B-test_2.csv
	-@./lab3b data/P3B-test_3.csv
	-@./lab3b data/P3B-test_4.csv
	-@./lab3b data/P3B-test_5.csv
	-@./lab3b data/P3B-test_6.csv
	-@./lab3b data/P3B-test_7.csv
	-@./lab3b data/P3B-test_8.csv
	-@./lab3b data/P3B-test_9.csv
	-@./lab3b data/P3B-test_10.csv
	-@./lab3b data/P3B-test_11.csv
	-@./lab3b data/P3B-test_12.csv
	-@./lab3b data/P3B-test_13.csv
	-@./lab3b data/P3B-test_14.csv
	-@./lab3b data/P3B-test_15.csv
	-@./lab3b data/P3B-test_16.csv
	-@./lab3b data/P3B-test_17.csv
	-@./lab3b data/P3B-test_18.csv
	-@./lab3b data/P3B-test_19.csv
	-@./lab3b data/P3B-test_20.csv
	-@./lab3b data/P3B-test_21.csv
	-@./lab3b data/P3B-test_22.csv


