0 0 dataAuditErrors
512 0 ptap_StampErrorFloat
513 0 ptap_StampErrorMult
519 0 psubstrate_StampErrorFloat
520 0 psubstrate_StampErrorMult
526 0 ntap_StampErrorFloat
527 0 ntap_StampErrorMult
533 0 nwell_conn_StampErrorFloat
534 0 nwell_conn_StampErrorMult
540 0 nb_tap_StampErrorFloat
541 0 nb_tap_StampErrorMult
547 0 Nburied_StampErrorFloat
548 0 Nburied_StampErrorMult
2206 0 malformed device _nmos_12
2207 0 malformed device _nmos_12_hvt
2208 0 malformed device _nmos_12_iso
2209 0 malformed device _nmos_12_native
2210 0 malformed device _nmos_25
2211 0 malformed device _nmos_25_native
2212 0 malformed device _pmos_12
2213 0 malformed device _pmos_12_hvt
2214 0 malformed device _pmos_25
2215 0 malformed device _pmoscap_12
2216 0 malformed device _pmoscap_25
2217 0 malformed device _pmoscap_12_3
2218 0 malformed device _pmoscap_25_3
2219 0 malformed device _nmoscap_12
2220 0 malformed device _nmoscap_25
2221 0 malformed device _nmoscap_12_3
2222 0 malformed device _nmoscap_25_3
2223 0 malformed device _rndiff
2224 0 malformed device _rndiff_nosal
2225 0 malformed device _rnpoly
2226 0 malformed device _rnpolynw
2227 0 malformed device _rnpoly_nosal
2228 0 malformed device _rnpolynw_nosal
2229 0 malformed device _rpdiff
2230 0 malformed device _rpdiff_nosal
2231 0 malformed device _rppoly
2232 0 malformed device _rppolynw
2233 0 malformed device _rppoly_nosal
2234 0 malformed device _rppolynw_nosal
2235 0 malformed device _rnwellsti
2236 0 malformed device _rnwellod
2237 0 malformed device _resm1
2238 0 malformed device _resm2
2239 0 malformed device _resm3
2240 0 malformed device _resm4
2241 0 malformed device _resm5
2242 0 malformed device _resm6
2243 0 malformed device _resm7
2244 0 malformed device _resm8
2245 0 malformed device _resm9
2246 0 malformed device _ndio
2247 0 malformed device _pdio
2248 0 malformed device _vpnp2
2249 0 malformed device _vpnp5
2250 0 malformed device _vpnp10
2251 0 malformed device _pnp
2252 0 malformed device _npn
2253 0 malformed device MIMCAP
2591 0 unstable device for MIMCAP_CAP_48
2592 0 unpreserved device MIMCAP_CAP_48
2593 0 unstable device for _npn_BJT_47
2594 0 unpreserved device _npn_BJT_47
2595 0 unstable device for _pnp_BJT_46
2596 0 unpreserved device _pnp_BJT_46
2597 0 unstable device for _vpnp10_BJT_45
2598 0 unpreserved device _vpnp10_BJT_45
2599 0 unstable device for _vpnp5_BJT_44
2600 0 unpreserved device _vpnp5_BJT_44
2601 0 unstable device for _vpnp2_BJT_43
2602 0 unpreserved device _vpnp2_BJT_43
2603 0 unstable device for _pdio_DIODE_42
2604 0 unpreserved device _pdio_DIODE_42
2605 0 unstable device for _ndio_DIODE_41
2606 0 unpreserved device _ndio_DIODE_41
2607 0 unstable device for _resm9_RES_40
2608 0 unpreserved device _resm9_RES_40
2609 0 unstable device for _resm8_RES_39
2610 0 unpreserved device _resm8_RES_39
2611 0 unstable device for _resm7_RES_38
2612 0 unpreserved device _resm7_RES_38
2613 0 unstable device for _resm6_RES_37
2614 0 unpreserved device _resm6_RES_37
2615 0 unstable device for _resm5_RES_36
2616 0 unpreserved device _resm5_RES_36
2617 0 unstable device for _resm4_RES_35
2618 0 unpreserved device _resm4_RES_35
2619 0 unstable device for _resm3_RES_34
2620 0 unpreserved device _resm3_RES_34
2621 0 unstable device for _resm2_RES_33
2622 0 unpreserved device _resm2_RES_33
2623 0 unstable device for _resm1_RES_32
2624 0 unpreserved device _resm1_RES_32
2625 0 unstable device for _rnwellod_RES_31
2626 0 unpreserved device _rnwellod_RES_31
2627 0 unstable device for _rnwellsti_RES_30
2628 0 unpreserved device _rnwellsti_RES_30
2629 0 unstable device for _rppolynw_nosal_RES_29
2630 0 unpreserved device _rppolynw_nosal_RES_29
2631 0 unstable device for _rppoly_nosal_RES_28
2632 0 unpreserved device _rppoly_nosal_RES_28
2633 0 unstable device for _rppolynw_RES_27
2634 0 unpreserved device _rppolynw_RES_27
2635 0 unstable device for _rppoly_RES_26
2636 0 unpreserved device _rppoly_RES_26
2637 0 unstable device for _rpdiff_nosal_RES_25
2638 0 unpreserved device _rpdiff_nosal_RES_25
2639 0 unstable device for _rpdiff_RES_24
2640 0 unpreserved device _rpdiff_RES_24
2641 0 unstable device for _rnpolynw_nosal_RES_23
2642 0 unpreserved device _rnpolynw_nosal_RES_23
2643 0 unstable device for _rnpoly_nosal_RES_22
2644 0 unpreserved device _rnpoly_nosal_RES_22
2645 0 unstable device for _rnpolynw_RES_21
2646 0 unpreserved device _rnpolynw_RES_21
2647 0 unstable device for _rnpoly_RES_20
2648 0 unpreserved device _rnpoly_RES_20
2649 0 unstable device for _rndiff_nosal_RES_19
2650 0 unpreserved device _rndiff_nosal_RES_19
2651 0 unstable device for _rndiff_RES_18
2652 0 unpreserved device _rndiff_RES_18
2653 0 unstable device for _nmoscap_25_3_MOS_17
2654 0 unpreserved device _nmoscap_25_3_MOS_17
2655 0 unstable device for _nmoscap_12_3_MOS_16
2656 0 unpreserved device _nmoscap_12_3_MOS_16
2657 0 unstable device for _nmoscap_25_MOS_15
2658 0 unpreserved device _nmoscap_25_MOS_15
2659 0 unstable device for _nmoscap_12_MOS_14
2660 0 unpreserved device _nmoscap_12_MOS_14
2661 0 unstable device for _pmoscap_25_3_MOS_13
2662 0 unpreserved device _pmoscap_25_3_MOS_13
2663 0 unstable device for _pmoscap_12_3_MOS_12
2664 0 unpreserved device _pmoscap_12_3_MOS_12
2665 0 unstable device for _pmoscap_25_MOS_11
2666 0 unpreserved device _pmoscap_25_MOS_11
2667 0 unstable device for _pmoscap_12_MOS_10
2668 0 unpreserved device _pmoscap_12_MOS_10
2669 0 unstable device for _pmos_25_MOS_9
2670 0 unpreserved device _pmos_25_MOS_9
2671 0 unstable device for _pmos_12_hvt_MOS_8
2672 0 unpreserved device _pmos_12_hvt_MOS_8
2673 0 unstable device for _pmos_12_MOS_7
2674 0 unpreserved device _pmos_12_MOS_7
2675 0 unstable device for _nmos_25_native_MOS_6
2676 0 unpreserved device _nmos_25_native_MOS_6
2677 0 unstable device for _nmos_25_MOS_5
2678 0 unpreserved device _nmos_25_MOS_5
2679 0 unstable device for _nmos_12_native_MOS_4
2680 0 unpreserved device _nmos_12_native_MOS_4
2681 0 unstable device for _nmos_12_iso_Device_3
2682 0 unpreserved device _nmos_12_iso_Device_3
2683 0 unstable device for _nmos_12_hvt_MOS_2
2684 0 unpreserved device _nmos_12_hvt_MOS_2
2685 0 unstable device for _nmos_12_MOS_1
2686 0 unpreserved device _nmos_12_MOS_1
