0 0 dataAuditErrors
151 0 offGridShapeErrors: off grid polygon on layer Bondpad
153 0 offGridShapeErrors: off grid polygon on layer CapMetal
155 0 offGridShapeErrors: off grid polygon on layer Cont
157 0 offGridShapeErrors: off grid polygon on layer ESDdummy
159 0 offGridShapeErrors: off grid polygon on layer IND2dummy
161 0 offGridShapeErrors: off grid polygon on layer IND3dummy
163 0 offGridShapeErrors: off grid polygon on layer INDdummy
165 0 offGridShapeErrors: off grid polygon on layer M1Resdum
167 0 offGridShapeErrors: off grid polygon on layer M2Resdum
169 0 offGridShapeErrors: off grid polygon on layer M3Resdum
171 0 offGridShapeErrors: off grid polygon on layer M4Resdum
173 0 offGridShapeErrors: off grid polygon on layer M5Resdum
175 0 offGridShapeErrors: off grid polygon on layer M6Resdum
177 0 offGridShapeErrors: off grid polygon on layer M7Resdum
179 0 offGridShapeErrors: off grid polygon on layer M8Resdum
181 0 offGridShapeErrors: off grid polygon on layer M9Resdum
183 0 offGridShapeErrors: off grid polygon on layer Metal1_d
185 0 offGridShapeErrors: off grid polygon on layer Metal1_f
187 0 offGridShapeErrors: off grid polygon on layer Metal1_n
189 0 offGridShapeErrors: off grid polygon on layer Metal1_p
191 0 offGridShapeErrors: off grid polygon on layer Metal1_slot
193 0 offGridShapeErrors: off grid polygon on layer Metal2_d
195 0 offGridShapeErrors: off grid polygon on layer Metal2_f
197 0 offGridShapeErrors: off grid polygon on layer Metal2_n
199 0 offGridShapeErrors: off grid polygon on layer Metal2_p
201 0 offGridShapeErrors: off grid polygon on layer Metal2_slot
203 0 offGridShapeErrors: off grid polygon on layer Metal3_d
205 0 offGridShapeErrors: off grid polygon on layer Metal3_f
207 0 offGridShapeErrors: off grid polygon on layer Metal3_n
209 0 offGridShapeErrors: off grid polygon on layer Metal3_p
211 0 offGridShapeErrors: off grid polygon on layer Metal3_slot
213 0 offGridShapeErrors: off grid polygon on layer Metal4_d
215 0 offGridShapeErrors: off grid polygon on layer Metal4_f
217 0 offGridShapeErrors: off grid polygon on layer Metal4_n
219 0 offGridShapeErrors: off grid polygon on layer Metal4_p
221 0 offGridShapeErrors: off grid polygon on layer Metal4_slot
223 0 offGridShapeErrors: off grid polygon on layer Metal5_d
225 0 offGridShapeErrors: off grid polygon on layer Metal5_f
227 0 offGridShapeErrors: off grid polygon on layer Metal5_n
229 0 offGridShapeErrors: off grid polygon on layer Metal5_p
231 0 offGridShapeErrors: off grid polygon on layer Metal5_slot
233 0 offGridShapeErrors: off grid polygon on layer Metal6_d
235 0 offGridShapeErrors: off grid polygon on layer Metal6_f
237 0 offGridShapeErrors: off grid polygon on layer Metal6_n
239 0 offGridShapeErrors: off grid polygon on layer Metal6_p
241 0 offGridShapeErrors: off grid polygon on layer Metal6_slot
243 0 offGridShapeErrors: off grid polygon on layer Metal7_d
245 0 offGridShapeErrors: off grid polygon on layer Metal7_f
247 0 offGridShapeErrors: off grid polygon on layer Metal7_n
249 0 offGridShapeErrors: off grid polygon on layer Metal7_p
251 0 offGridShapeErrors: off grid polygon on layer Metal7_slot
253 0 offGridShapeErrors: off grid polygon on layer Metal8_d
255 0 offGridShapeErrors: off grid polygon on layer Metal8_f
257 0 offGridShapeErrors: off grid polygon on layer Metal8_n
259 0 offGridShapeErrors: off grid polygon on layer Metal8_p
261 0 offGridShapeErrors: off grid polygon on layer Metal8_slot
263 0 offGridShapeErrors: off grid polygon on layer Metal9_d
265 0 offGridShapeErrors: off grid polygon on layer Metal9_f
267 0 offGridShapeErrors: off grid polygon on layer Metal9_n
269 0 offGridShapeErrors: off grid polygon on layer Metal9_p
271 0 offGridShapeErrors: off grid polygon on layer Metal9_slot
273 0 offGridShapeErrors: off grid polygon on layer NPNdummy
275 0 offGridShapeErrors: off grid polygon on layer Nburied
277 0 offGridShapeErrors: off grid polygon on layer Nhvt
279 0 offGridShapeErrors: off grid polygon on layer Nimp
281 0 offGridShapeErrors: off grid polygon on layer Nwell
283 0 offGridShapeErrors: off grid polygon on layer Nzvt
285 0 offGridShapeErrors: off grid polygon on layer Oxide
287 0 offGridShapeErrors: off grid polygon on layer Oxide_thk
289 0 offGridShapeErrors: off grid polygon on layer PNPdummy
291 0 offGridShapeErrors: off grid polygon on layer Phvt
293 0 offGridShapeErrors: off grid polygon on layer Pimp
295 0 offGridShapeErrors: off grid polygon on layer Poly
297 0 offGridShapeErrors: off grid polygon on layer Psub
299 0 offGridShapeErrors: off grid polygon on layer ResWdum
301 0 offGridShapeErrors: off grid polygon on layer Resdum
303 0 offGridShapeErrors: off grid polygon on layer SiProt
305 0 offGridShapeErrors: off grid polygon on layer Via1
307 0 offGridShapeErrors: off grid polygon on layer Via2
309 0 offGridShapeErrors: off grid polygon on layer Via3
311 0 offGridShapeErrors: off grid polygon on layer Via4
313 0 offGridShapeErrors: off grid polygon on layer Via5
315 0 offGridShapeErrors: off grid polygon on layer Via6
317 0 offGridShapeErrors: off grid polygon on layer Via7
319 0 offGridShapeErrors: off grid polygon on layer Via8
321 0 non45 degree polygon on layer Bondpad
323 0 non45 degree polygon on layer CapMetal
325 0 non45 degree polygon on layer Cont
327 0 non45 degree polygon on layer ESDdummy
329 0 non45 degree polygon on layer IND2dummy
331 0 non45 degree polygon on layer IND3dummy
333 0 non45 degree polygon on layer INDdummy
335 0 non45 degree polygon on layer M1Resdum
337 0 non45 degree polygon on layer M2Resdum
339 0 non45 degree polygon on layer M3Resdum
341 0 non45 degree polygon on layer M4Resdum
343 0 non45 degree polygon on layer M5Resdum
345 0 non45 degree polygon on layer M6Resdum
347 0 non45 degree polygon on layer M7Resdum
349 0 non45 degree polygon on layer M8Resdum
351 0 non45 degree polygon on layer M9Resdum
353 0 non45 degree polygon on layer Metal1_d
355 0 non45 degree polygon on layer Metal1_f
357 0 non45 degree polygon on layer Metal1_n
359 0 non45 degree polygon on layer Metal1_p
361 0 non45 degree polygon on layer Metal1_slot
363 0 non45 degree polygon on layer Metal2_d
365 0 non45 degree polygon on layer Metal2_f
367 0 non45 degree polygon on layer Metal2_n
369 0 non45 degree polygon on layer Metal2_p
371 0 non45 degree polygon on layer Metal2_slot
373 0 non45 degree polygon on layer Metal3_d
375 0 non45 degree polygon on layer Metal3_f
377 0 non45 degree polygon on layer Metal3_n
379 0 non45 degree polygon on layer Metal3_p
381 0 non45 degree polygon on layer Metal3_slot
383 0 non45 degree polygon on layer Metal4_d
385 0 non45 degree polygon on layer Metal4_f
387 0 non45 degree polygon on layer Metal4_n
389 0 non45 degree polygon on layer Metal4_p
391 0 non45 degree polygon on layer Metal4_slot
393 0 non45 degree polygon on layer Metal5_d
395 0 non45 degree polygon on layer Metal5_f
397 0 non45 degree polygon on layer Metal5_n
399 0 non45 degree polygon on layer Metal5_p
401 0 non45 degree polygon on layer Metal5_slot
403 0 non45 degree polygon on layer Metal6_d
405 0 non45 degree polygon on layer Metal6_f
407 0 non45 degree polygon on layer Metal6_n
409 0 non45 degree polygon on layer Metal6_p
411 0 non45 degree polygon on layer Metal6_slot
413 0 non45 degree polygon on layer Metal7_d
415 0 non45 degree polygon on layer Metal7_f
417 0 non45 degree polygon on layer Metal7_n
419 0 non45 degree polygon on layer Metal7_p
421 0 non45 degree polygon on layer Metal7_slot
423 0 non45 degree polygon on layer Metal8_d
425 0 non45 degree polygon on layer Metal8_f
427 0 non45 degree polygon on layer Metal8_n
429 0 non45 degree polygon on layer Metal8_p
431 0 non45 degree polygon on layer Metal8_slot
433 0 non45 degree polygon on layer Metal9_d
435 0 non45 degree polygon on layer Metal9_f
437 0 non45 degree polygon on layer Metal9_n
439 0 non45 degree polygon on layer Metal9_p
441 0 non45 degree polygon on layer Metal9_slot
443 0 non45 degree polygon on layer NPNdummy
445 0 non45 degree polygon on layer Nburied
447 0 non45 degree polygon on layer Nhvt
449 0 non45 degree polygon on layer Nimp
451 0 non45 degree polygon on layer Nwell
453 0 non45 degree polygon on layer Nzvt
455 0 non45 degree polygon on layer Oxide
457 0 non45 degree polygon on layer Oxide_thk
459 0 non45 degree polygon on layer PNPdummy
461 0 non45 degree polygon on layer Phvt
463 0 non45 degree polygon on layer Pimp
465 0 non45 degree polygon on layer Poly
467 0 non45 degree polygon on layer Psub
469 0 non45 degree polygon on layer ResWdum
471 0 non45 degree polygon on layer Resdum
473 0 non45 degree polygon on layer SiProt
475 0 non45 degree polygon on layer Via1
477 0 non45 degree polygon on layer Via2
479 0 non45 degree polygon on layer Via3
481 0 non45 degree polygon on layer Via4
483 0 non45 degree polygon on layer Via5
485 0 non45 degree polygon on layer Via6
487 0 non45 degree polygon on layer Via7
489 0 non45 degree polygon on layer Via8
490 0 acute angle on layer Bondpad
491 0 acute angle on layer CapMetal
492 0 acute angle on layer ESDdummy
493 0 acute angle on layer IND2dummy
494 0 acute angle on layer IND3dummy
495 0 acute angle on layer INDdummy
496 0 acute angle on layer M1Resdum
497 0 acute angle on layer M2Resdum
498 0 acute angle on layer M3Resdum
499 0 acute angle on layer M4Resdum
500 0 acute angle on layer M5Resdum
501 0 acute angle on layer M6Resdum
502 0 acute angle on layer M7Resdum
503 0 acute angle on layer M8Resdum
504 0 acute angle on layer M9Resdum
505 0 acute angle on layer Metal1_d
506 0 acute angle on layer Metal1_f
507 0 acute angle on layer Metal1_n
508 0 acute angle on layer Metal1_p
509 0 acute angle on layer Metal1_slot
510 0 acute angle on layer Metal2_d
511 0 acute angle on layer Metal2_f
512 0 acute angle on layer Metal2_n
513 0 acute angle on layer Metal2_p
514 0 acute angle on layer Metal2_slot
515 0 acute angle on layer Metal3_d
516 0 acute angle on layer Metal3_f
517 0 acute angle on layer Metal3_n
518 0 acute angle on layer Metal3_p
519 0 acute angle on layer Metal3_slot
520 0 acute angle on layer Metal4_d
521 0 acute angle on layer Metal4_f
522 0 acute angle on layer Metal4_n
523 0 acute angle on layer Metal4_p
524 0 acute angle on layer Metal4_slot
525 0 acute angle on layer Metal5_d
526 0 acute angle on layer Metal5_f
527 0 acute angle on layer Metal5_n
528 0 acute angle on layer Metal5_p
529 0 acute angle on layer Metal5_slot
530 0 acute angle on layer Metal6_d
531 0 acute angle on layer Metal6_f
532 0 acute angle on layer Metal6_n
533 0 acute angle on layer Metal6_p
534 0 acute angle on layer Metal6_slot
535 0 acute angle on layer Metal7_d
536 0 acute angle on layer Metal7_f
537 0 acute angle on layer Metal7_n
538 0 acute angle on layer Metal7_p
539 0 acute angle on layer Metal7_slot
540 0 acute angle on layer Metal8_d
541 0 acute angle on layer Metal8_f
542 0 acute angle on layer Metal8_n
543 0 acute angle on layer Metal8_p
544 0 acute angle on layer Metal8_slot
545 0 acute angle on layer Metal9_d
546 0 acute angle on layer Metal9_f
547 0 acute angle on layer Metal9_n
548 0 acute angle on layer Metal9_p
549 0 acute angle on layer Metal9_slot
550 0 acute angle on layer NPNdummy
551 0 acute angle on layer Nhvt
552 0 acute angle on layer PNPdummy
553 0 acute angle on layer Phvt
554 0 acute angle on layer Psub
555 0 acute angle on layer ResWdum
556 0 acute angle on layer Resdum
2892 0 ptap_StampErrorFloat
2893 0 ptap_StampErrorMult
2899 0 psubstrate_StampErrorFloat
2900 0 psubstrate_StampErrorMult
2906 0 ntap_StampErrorFloat
2907 0 ntap_StampErrorMult
2913 0 nwell_conn_StampErrorFloat
2914 0 nwell_conn_StampErrorMult
2920 0 nb_tap_StampErrorFloat
2921 0 nb_tap_StampErrorMult
2927 0 Nburied_StampErrorFloat
2928 0 Nburied_StampErrorMult
2967 0 NBL.W.1: Nburied width must be >= 3.2 um
2969 0 NBL.E.1: Nburied to Nwell enclosure must be >= 0.4 um
2971 0 NBL.SP.1: Nburied to Nburied spacing must be >= 5.0 um
2974 0 NBL.SE.2: Nburied to Oxide spacing must be >= 2.2 um
2975 0 NBL.SE.2: Nburied to Oxide spacing must be >= 2.2 um
2976 0 NBL.SE.1: Nburied to non-related Nwell spacing must be >= 4.4 um
2981 0 NBL.SE.3: Nwell ring (on Nburied) to P+ Oxide spacing must be >= 0.5 um
2983 0 NBL.SE.3: Nwell ring (on Nburied) to P+ Oxide spacing must be >= 0.5 um
2987 0 NBL.SE.4: Nwell ring (on Nburied) to N+ Oxide spacing must be >= 0.4 um
2989 0 NBL.SE.4: Nwell ring (on Nburied) to N+ Oxide spacing must be >= 0.4 um
2990 0 NBL.X.1: Nburied must have an Nwell isolation ring
2992 0 NW.SP.1: Nwell to Nwell spacing (same potential) must be >= 0.6 um
2994 0 NW.SP.1: Nwell to Nwell spacing (same potential) must be >= 0.6 um
2997 0 NW.SP.2: Nwell to Nwell spacing (diferent potential) must be >= 1.2 um
2998 0 NW.SP.2: Nwell to Nwell spacing (diferent potential) must be >= 1.2 um
3000 0 NW.SP.2: Nwell to Nwell spacing (diferent potential) must be >= 1.2 um
3001 0 NW.W.1: Nwell width must be >= 0.6 um
3003 0 NW.SP.2: Nwell to Nwell spacing (diferent potential) must be >= 1.2 um
3004 0 NW.SE.1: Nwell to Oxide spacing must be >= 0.3 um
3007 0 NW.SE.2: Nwell to P+ Oxide spacing must be >= 0.3 um
3008 0 NW.SE.2: Nwell to P+ Oxide spacing must be >= 0.3 um
3013 0 NW.SE.3: Nwell to N+ 2.5V Oxide spacing must be >= 0.5 um
3014 0 NW.SE.3: Nwell to N+ 2.5V Oxide spacing must be >= 0.5 um
3019 0 NW.SE.4: Nwell to P+ 2.5V Oxide spacing must be >= 0.5 um
3020 0 NW.SE.4: Nwell to P+ 2.5V Oxide spacing must be >= 0.5 um
3025 0 NW.E.1: Nwell to N+ Oxide enclosure must be >= 0.12 um
3026 0 NW.E.2: Nwell to P+ Oxide enclosure must be >= 0.12 um
3028 0 NW.E.2: Nwell to P+ Oxide enclosure must be >= 0.12 um
3029 0 NW.E.3: Nwell to N+ 2.5V Oxide enclosure must be >= 0.7 um
3031 0 NW.E.3: Nwell to N+ 2.5V Oxide enclosure must be >= 0.7 um
3032 0 NW.E.4: Nwell to P+ 2.5V Oxide enclosure must be >= 0.7 um
3034 0 NW.E.4: Nwell to P+ 2.5V Oxide enclosure must be >= 0.7 um
3035 0 NWR.SE.1: Nwell (in resistor) to SiProt spacing must be >= 0.32 um
3037 0 NWR.E.1: Oxide to Nwell (in resistor) enclosure must be >= 1.2 um
3039 0 NWR.E.1: Oxide to Nwell (in resistor) enclosure must be >= 1.2 um
3041 0 NWR.E.2: Nwell (in resistor) to Cont enclosure must be >= 0.32 um
3043 0 NWR.E.2: Nwell (in resistor) to Cont enclosure must be >= 0.32 um
3044 0 NWR.O.1: SiProt to Nimp overlap must be >= 0.45 um
3045 0 NWR.X.1: Thick Oxide is NOT allowed over Nwell resistor
3046 0 OXIDE.W.1: Oxide width must be >= 0.1 um
3051 0 OXIDE.W.2.1.1: 1.2V N-channel gate width must be >= 0.12 um
3055 0 OXIDE.W.2.1.2: 2.5V N-channel gate width must be >= 0.15 um
3060 0 OXIDE.W.2.2.1: 1.2V P-channel gate width must be >= 0.12 um
3064 0 OXIDE.W.2.2.2: 2.5V P-channel gate width must be >= 0.15 um
3066 0 OXIDE.W.3: Oxide (45 degree) width must be >= 0.13 um
3068 0 OXIDE.SP.1: N+ Oxide to N+ Oxide spacing must be >= 0.15 um
3070 0 OXIDE.SP.2: P+ Oxide to P+ Oxide spacing must be >= 0.15 um
3075 0 OXIDE.SP.3: P+ Oxide to P+ Oxide spacing must be >= 0.15 um
3076 0 OXIDE.SE.1: Oxide to Oxide_thk spacing must be >= 0.28 um
3077 0 OXIDE.SP.4: Oxide bent 45 degree to Oxide spacing must be >= 0.18 um
3078 0 OXIDE.A.1: Oxide area must be >= 0.06 um
3082 0 OXIDE.EA.1: Oxide enclosed area must be >= 0.10 um
3083 0 OXIDE.L.1_OXIDE.L.2: Maximum Oxide length between two contacts (when the Oxide width is <= 0.18um) must be <= 22.0um and Maximum Oxide length between one contact and the end of the Oxide line (when the Oxide width is <= 0.18um) must be <= 11.0um
3087 0 OXIDE.X.1: Oxide must be covered by Nimp or Pimp or Nzvt
3093 0 OXIDER.SE.1: SiProt to Oxide resistor Cont spacing must be >= 0.25 um
3094 0 OXIDER.SE.1: SiProt to Oxide resistor Cont spacing must be >= 0.25 um
3097 0 OXIDER.SE.2: Oxide resistor to Nimp spacing must be >= 0.3 um
3098 0 OXIDER.SE.2: Oxide resistor to Nimp spacing must be >= 0.3 um
3101 0 OXIDER.SE.2: Oxide resistor to Pimp spacing must be >= 0.3 um
3102 0 OXIDER.SE.2: Oxide resistor to Pimp spacing must be >= 0.3 um
3104 0 OXIDER.E.1: SiProt to Oxide resistor enclosure must be >= 0.25 um
3106 0 OXIDER.X.1: Oxide resistors must have N+ or P+ Implant
3107 0 OXIDETHK.W.1: Oxide_thk width must be >= 0.7 um
3109 0 OXIDETHK.SP.1: Oxide_thk to Oxide_thk spacing must be >= 0.35 um
3111 0 OXIDETHK.SP.2: Oxide_thk (bent 45 degree) to Oxide_thk spacing must be >= 0.75 um
3113 0 OXIDETHK.SE.1: 2.5V N+ Oxide to 2.5V N+ Oxide spacing must be >= 0.20 um
3115 0 OXIDETHK.SE.2: 2.5V P+ Oxide to 2.5V P+ Oxide spacing must be >= 0.20 um
3120 0 OXIDETHK.SE.3: 2.5V N+ Oxide to 2.5V P+ Oxide spacing must be >= 0.25 um
3122 0 OXIDETHK.E.1: Oxide_thk to Oxide enclosure must be >= 0.30 um
3129 0 OXIDETHK.SE.5: Oxide_thk to Poly gate spacing must be >= 0.34 um
3130 0 OXIDETHK.SE.5: Oxide_thk to Poly gate spacing must be >= 0.34 um
3132 0 OXIDETHK.E.2: Oxide_thk to Poly gate enclosure must be >= 0.36 um
3133 0 NHVT.X.1: Nhvt to Oxide enclosure must be == 0.0 on all sides
3134 0 NHVT.X.2: Nhvt is NOT allowed on Nwell
3135 0 NHVT.X.3: Nhvt is NOT allowed on P+ Oxide
3136 0 NHVT.X.4: Nhvt is NOT allowed on Nzvt
3137 0 PHVT.X.1: Phvt to Oxide enclosure must be == 0.0 on all sides
3138 0 PHVT.X.2: Phvt is NOT allowed outside Nwell
3139 0 PHVT.X.3: Phvt is NOT allowed on N+ Oxide
3140 0 PHVT.X.4: Phvt is NOT allowed on Nzvt
3141 0 NZVT.W.1: Nzvt width must be >= 0.7 um
3143 0 NZVT.SP.1: Nzvt to Nzvt spacing must be >= 0.6 um
3144 0 NZVT.O.1: Nzvt to Oxide enclosure must be == 0.3
3147 0 NZVT.SE.1: Nzvt to Oxide spacing must be >= 0.4 um
3148 0 NZVT.SE.1: Nzvt to Oxide spacing must be >= 0.4 um
3149 0 NZVT.SE.2: Nzvt to Nwell spacing must be >= 1.2 um
3150 0 NZVT.SE.2: Nzvt to Nwell spacing must be >= 1.2 um
3153 0 NZVT.E.1: Poly to Oxide enclosure must be >= 0.2 um
3156 0 NZVT.L.1: Native Device Poly gate length must be >= 0.9 um
3160 0 NZVT.W.2: Native Device Poly gate width must be >= 0.65 um
3162 0 NZVT.X.3: P+ Oxide is NOT allowed in Nzvt
3163 0 NZVT.X.4: Only one Oxide region may be in an Nzvt region
3166 0 POLY.W.1: 1.2V N+ Poly gate length must be >= 0.1 um
3169 0 POLY.W.2: 1.2V P+ Poly gate length must be >= 0.1 um
3173 0 POLY.W.3: 2.5V N+ Poly gate length must be >= 0.28 um
3178 0 POLY.W.4: 2.5V P+ Poly gate length must be >= 0.28 um
3181 0 POLY.W.5: Poly interconnect width must be >= 0.1 um
3185 0 POLY.SP.1: Poly resistor to Poly resistor spacing must be >= 0.6 um
3187 0 POLY.SP.2: Poly gate to Poly gate spacing must be >= 0.12 um
3189 0 POLY.SP.3: Poly interconnect to Poly interconnect spacing must be >= 0.12 um
3191 0 POLY.E.1: Poly to N+ Oxide enclosure must be >= 0.18 um
3193 0 POLY.E.2: Poly to P+ Oxide enclosure must be >= 0.18 um
3194 0 POLY.SE.1_POLY.SE.2: Poly to Oxide spacing must be >= 0.1 um
3196 0 POLY.E.3: Oxide to Poly enclosure must be >= 0.2 um
3198 0 POLY.W.6: Bent Poly width must be >= 0.18 um
3200 0 POLY.SP.4: Bent Poly to bent Poly spacing must be >= 0.22 um
3201 0 POLY.X.1: Poly gate cannot have bends
3202 0 POLY.X.2: Poly resistor cannot have bends
3203 0 POLY.SE.3: Poly width, between two contacts spaced > 25.0um, must be >= 0.14um
3204 0 POLY.A.1: Poly area must be >= 0.1 um
3210 0 POLYR.SE.1: SiProt to Poly resistor Cont spacing must be >= 0.25 um
3211 0 POLYR.SE.1: SiProt to Poly resistor Cont spacing must be >= 0.25 um
3213 0 POLYR.E.1: SiProt to Poly resistor enclosure must be >= 0.28 um
3215 0 POLYR.E.2: Nimp to Poly used in resistor enclosure must be >= 0.15 um
3217 0 POLYR.E.2: Nimp to Poly used in resistor enclosure must be >= 0.15 um
3219 0 POLYR.E.3: Pimp to Poly used in resistor enclosure must be >= 0.15 um
3221 0 POLYR.E.3: Pimp to Poly used in resistor enclosure must be >= 0.15 um
3223 0 POLYR.SE.2: Poly resistor to Nimp spacing must be >= 0.3 um
3224 0 POLYR.SE.2: Poly resistor to Nimp spacing must be >= 0.3 um
3225 0 POLYR.SE.2: Poly resistor to Nzvt spacing must be >= 0.3 um
3226 0 POLYR.SE.2: Poly resistor to Nzvt spacing must be >= 0.3 um
3228 0 POLYR.SE.2: Poly resistor to Pimp spacing must be >= 0.3 um
3229 0 POLYR.SE.2: Poly resistor to Pimp spacing must be >= 0.3 um
3230 0 POLYR.X.1: Poly resistors must have N+ or P+ Implant
3231 0 NIMP.W.1: Nimp width must be >= 0.24 um
3233 0 NIMP.SP.1: Nimp to Nimp spacing must be >= 0.24 um
3236 0 NIMP.E.1: Nimp to Oxide enclosure must be >= 0.14 um
3237 0 NIMP.O.1: Nimp to Oxide overlap must be >= 0.16 um
3245 0 NIMP.SE.1: Nimp to P+ Oxide spacing must be >= 0.16 um
3246 0 NIMP.SE.1: Nimp to P+ Oxide spacing must be >= 0.16 um
3249 0 NIMP.E.2: Nimp to Oxide (Nwell tie) enclosure must be >= 0.02 um
3253 0 NIMP.E.3: Nimp to Poly gate enclosure must be >= 0.18 um
3259 0 NIMP.E.4: Nimp to gate end enclosure must be >= 0.18 um
3261 0 NIMP.E.4: Nimp to gate end enclosure must be >= 0.18 um
3270 0 NIMP.SE.2: Nimp to P+ Oxide spacing must be >= 0.02 um
3271 0 NIMP.SE.2: Nimp to P+ Oxide spacing must be >= 0.02 um
3272 0 NIMP.A.1: Nimp area must be >= 0.15 um
3276 0 NIMP.EA.1: Area in Nimp ring must be >= 0.16 um
3279 0 NIMP.SE.3: Nimp to P+ gate spacing must be >= 0.18 um
3280 0 NIMP.SE.3: Nimp to P+ gate spacing must be >= 0.18 um
3281 0 NIMP.X.1: Nimp is NOT allowed over Pimp
3282 0 PIMP.W.1: Pimp width must be >= 0.24 um
3284 0 PIMP.SP.1: Pimp to Pimp spacing must be >= 0.24 um
3286 0 PIMP.E.1: Pimp to Oxide enclosure must be >= 0.14 um
3287 0 PIMP.O.1: Pimp to Oxide overlap must be >= 0.16 um
3295 0 PIMP.SE.1: Pimp to N+ Oxide spacing must be >= 0.16 um
3296 0 PIMP.SE.1: Pimp to N+ Oxide spacing must be >= 0.16 um
3298 0 PIMP.E.2: Pimp to Oxide (substrate tie) enclosure must be >= 0.02 um
3302 0 PIMP.E.3: Pimp to Poly gate enclosure must be >= 0.18 um
3305 0 PIMP.E.4: Pimp to gate end enclosure must be >= 0.18 um
3307 0 PIMP.E.4: Pimp to gate end enclosure must be >= 0.18 um
3316 0 PIMP.SE.2: Pimp to N+ Oxide spacing must be >= 0.02 um
3317 0 PIMP.SE.2: Pimp to N+ Oxide spacing must be >= 0.02 um
3318 0 PIMP.A.1: Pimp area must be >= 0.15 um
3322 0 PIMP.EA.1: Area in Pimp ring must be >= 0.16 um
3325 0 PIMP.SE.3: Pimp to N+ gate spacing must be >= 0.18 um
3326 0 PIMP.SE.3: Pimp to N+ gate spacing must be >= 0.18 um
3328 0 CONT.W.1: Cont shapes must be 0.12x0.12 rectangles
3330 0 CONT.SP.1: Cont to Cont spacing must be >= 0.14 um
3333 0 CONT.SP.2: Cont to Cont (in array) spacing must be >= 0.16 um
3336 0 CONT.SE.1: Cont to gate spacing must be >= 0.10 um
3337 0 CONT.SE.1: Cont to gate spacing must be >= 0.10 um
3343 0 CONT.SE.2: Cont to 2.5V gate spacing must be >= 0.12 um
3344 0 CONT.SE.2: Cont to 2.5V gate spacing must be >= 0.12 um
3346 0 CONT.SE.3: Poly Cont to Oxide spacing must be >= 0.12 um
3347 0 CONT.SE.3: Poly Cont to Oxide spacing must be >= 0.12 um
3352 0 CONT.SE.4: Poly Cont to Oxide spacing must be >= 0.14 um
3353 0 CONT.SE.4: Poly Cont to Oxide spacing must be >= 0.14 um
3355 0 CONT.E.1: Oxide to Cont enclosure must be >= 0.06 um
3357 0 CONT.E.1: Oxide to Cont enclosure must be >= 0.06 um
3359 0 CONT.E.2: Poly to Cont enclosure must be >= 0.04 um
3361 0 CONT.E.2: Poly to Cont enclosure must be >= 0.04 um
3364 0 CONT.E.3: Poly to Cont enclosure on at least two opposite sides must be >= 0.06 um
3366 0 CONT.E.4: Nimp to Cont enclosure must be >= 0.06 um
3368 0 CONT.E.4: Nimp to Cont enclosure must be >= 0.06 um
3370 0 CONT.E.4: Pimp to Cont enclosure must be >= 0.06 um
3372 0 CONT.E.4: Pimp to Cont enclosure must be >= 0.06 um
3374 0 CONT.X.1: Cont on gate is NOT allowed
3377 0 CONT.X.2: Nimp edge is NOT allowed on Oxide Cont
3380 0 CONT.X.2: Pimp edge is NOT allowed on Oxide Cont
3381 0 CONT.X.3: Cont must be covered by Oxide or Poly
3382 0 SIPROT.W.1: SiProt width must be >= 0.44 um
3384 0 SIPROT.SP.1: SiProt to SiProt spacing must be >= 0.44 um
3387 0 SIPROT.SE.1: SiProt to Cont spacing must be >= 0.24 um
3388 0 SIPROT.SE.1: SiProt to Cont spacing must be >= 0.24 um
3389 0 SIPROT.SE.2: SiProt to Oxide spacing must be >= 0.24 um
3393 0 SIPROT.SE.3: SiProt to Poly gate spacing must be >= 0.44 um
3394 0 SIPROT.SE.3: SiProt to Poly gate spacing must be >= 0.44 um
3396 0 SIPROT.E.2: Oxide to SiProt enclosure must be >= 0.24 um
3400 0 SIPROT.E.1: SiProt to Oxide enclosure must be >= 0.25 um
3402 0 SIPROT.E.3: SiProt to Poly enclosure must be >= 0.28 um
3403 0 SIPROT.A.1: SiProt area must be >= 1.2 um
3404 0 SIPROT.SE.4: SiProt to Poly (on field) spacing must be >= 0.35 um
3408 0 SIPROT.EA.1: Area in SiProt ring must be >= 1.2 um
3409 0 METAL2.E.1: Metal2 to Via1 enclosure must be >= 0.005 um
3411 0 METAL2.E.1: Metal2 to Via1 enclosure must be >= 0.005 um
3415 0 METAL2.E.2: Metal2 to Via1 enclosure on opposite sides must be >= 0.06 um
3416 0 METAL3.E.1: Metal3 to Via2 enclosure must be >= 0.005 um
3418 0 METAL3.E.1: Metal3 to Via2 enclosure must be >= 0.005 um
3422 0 METAL3.E.2: Metal3 to Via2 enclosure on opposite sides must be >= 0.06 um
3423 0 METAL4.E.1: Metal4 to Via3 enclosure must be >= 0.005 um
3425 0 METAL4.E.1: Metal4 to Via3 enclosure must be >= 0.005 um
3429 0 METAL4.E.2: Metal4 to Via3 enclosure on opposite sides must be >= 0.06 um
3430 0 METAL5.E.1: Metal5 to Via4 enclosure must be >= 0.005 um
3432 0 METAL5.E.1: Metal5 to Via4 enclosure must be >= 0.005 um
3436 0 METAL5.E.2: Metal5 to Via4 enclosure on opposite sides must be >= 0.06 um
3437 0 METAL6.E.1: Metal6 to Via5 enclosure must be >= 0.005 um
3439 0 METAL6.E.1: Metal6 to Via5 enclosure must be >= 0.005 um
3443 0 METAL6.E.2: Metal6 to Via5 enclosure on opposite sides must be >= 0.06 um
3444 0 METAL7.E.1: Metal7 to Via6 enclosure must be >= 0.005 um
3446 0 METAL7.E.1: Metal7 to Via6 enclosure must be >= 0.005 um
3450 0 METAL7.E.2: Metal7 to Via6 enclosure on opposite sides must be >= 0.06 um
3451 0 METAL8.E.1: Metal8 to Via7 enclosure must be >= 0.05 um
3453 0 METAL8.E.1: Metal8 to Via7 enclosure must be >= 0.05 um
3457 0 METAL8.E.2: Metal8 to Via7 enclosure on opposite sides must be >= 0.1 um
3458 0 METAL9.E.1: Metal9 to Via8 enclosure must be >= 0.05 um
3460 0 METAL9.E.1: Metal9 to Via8 enclosure must be >= 0.05 um
3464 0 METAL9.E.2: Metal9 to Via8 enclosure on opposite sides must be >= 0.1 um
3465 0 METAL1.E.1: Metal1 to Cont enclosure must be >= 0.00 um
3469 0 METAL1.E.2: Metal1 to Cont enclosure on opposite sides must be >= 0.06 um
3470 0 METAL1.W.1: Metal1 width must be >= 0.12 um
3471 0 METAL2.W.1: Metal2 width must be >= 0.14 um
3472 0 METAL3.W.1: Metal3 width must be >= 0.14 um
3473 0 METAL4.W.1: Metal4 width must be >= 0.14 um
3474 0 METAL5.W.1: Metal5 width must be >= 0.14 um
3475 0 METAL6.W.1: Metal6 width must be >= 0.14 um
3476 0 METAL7.W.1: Metal7 width must be >= 0.14 um
3477 0 METAL8.W.1: Metal8 width must be >= 0.44 um
3478 0 METAL9.W.1: Metal9 width must be >= 0.44 um
3482 0 METAL1.W.2: Metal1 width must be <= 12.0 um
3486 0 METAL2.W.2: Metal2 width must be <= 12.0 um
3490 0 METAL3.W.2: Metal3 width must be <= 12.0 um
3494 0 METAL4.W.2: Metal4 width must be <= 12.0 um
3498 0 METAL5.W.2: Metal5 width must be <= 12.0 um
3502 0 METAL6.W.2: Metal6 width must be <= 12.0 um
3505 0 METAL7.W.2: Metal7 width must be <= 12.0 um
3507 0 METAL8.W.2: Metal8 width must be <= 12.0 um
3509 0 METAL9.W.2: Metal9 width must be <= 12.0 um
3511 0 METAL1.SP.1.1: Metal1 to Metal1 spacing must be >= 0.12 um
3513 0 METAL2.SP.1.1: Metal2 to Metal2 spacing must be >= 0.14 um
3515 0 METAL3.SP.1.1: Metal3 to Metal3 spacing must be >= 0.14 um
3517 0 METAL4.SP.1.1: Metal4 to Metal4 spacing must be >= 0.14 um
3519 0 METAL5.SP.1.1: Metal5 to Metal5 spacing must be >= 0.14 um
3521 0 METAL6.SP.1.1: Metal6 to Metal6 spacing must be >= 0.14 um
3523 0 METAL7.SP.1.1: Metal7 to Metal7 spacing must be >= 0.14 um
3525 0 METAL8.SP.1.1: Metal8 to Metal8 spacing must be >= 0.40 um
3527 0 METAL9.SP.1.1: Metal9 to Metal9 spacing must be >= 0.40 um
3532 0 METAL1.SP.1.2: Metal1 to Metal1 spacing must be >= 0.18 um
3537 0 METAL2.SP.1.2: Metal2 to Metal2 spacing must be >= 0.20 um
3542 0 METAL3.SP.1.2: Metal3 to Metal3 spacing must be >= 0.20 um
3547 0 METAL4.SP.1.2: Metal4 to Metal4 spacing must be >= 0.20 um
3552 0 METAL5.SP.1.2: Metal5 to Metal5 spacing must be >= 0.20 um
3557 0 METAL6.SP.1.2: Metal6 to Metal6 spacing must be >= 0.20 um
3562 0 METAL7.SP.1.2: Metal7 to Metal7 spacing must be >= 0.20 um
3567 0 METAL1.SP.1.3: Metal1 to Metal1 spacing must be >= 0.50 um
3572 0 METAL2.SP.1.3: Metal2 to Metal2 spacing must be >= 0.50 um
3577 0 METAL3.SP.1.3: Metal3 to Metal3 spacing must be >= 0.50 um
3582 0 METAL4.SP.1.3: Metal4 to Metal4 spacing must be >= 0.50 um
3587 0 METAL5.SP.1.3: Metal5 to Metal5 spacing must be >= 0.50 um
3592 0 METAL6.SP.1.3: Metal6 to Metal6 spacing must be >= 0.50 um
3597 0 METAL7.SP.1.3: Metal7 to Metal7 spacing must be >= 0.50 um
3602 0 METAL8.SP.1.2: Metal8 to Metal8 spacing must be >= 0.50 um
3607 0 METAL9.SP.1.2: Metal9 to Metal9 spacing must be >= 0.50 um
3612 0 METAL1.SP.1.4: Metal1 to Metal1 spacing must be >= 0.90 um
3617 0 METAL2.SP.1.4: Metal2 to Metal2 spacing must be >= 0.90 um
3622 0 METAL3.SP.1.4: Metal3 to Metal3 spacing must be >= 0.90 um
3627 0 METAL4.SP.1.4: Metal4 to Metal4 spacing must be >= 0.90 um
3632 0 METAL5.SP.1.4: Metal5 to Metal5 spacing must be >= 0.90 um
3637 0 METAL6.SP.1.4: Metal6 to Metal6 spacing must be >= 0.90 um
3642 0 METAL7.SP.1.4: Metal7 to Metal7 spacing must be >= 0.90 um
3647 0 METAL8.SP.1.3: Metal8 to Metal8 spacing must be >= 0.90 um
3652 0 METAL9.SP.1.3: Metal9 to Metal9 spacing must be >= 0.90 um
3657 0 METAL1.SP.1.5: Metal1 to Metal1 spacing must be >= 1.50 um
3662 0 METAL2.SP.1.5: Metal2 to Metal2 spacing must be >= 1.50 um
3667 0 METAL3.SP.1.5: Metal3 to Metal3 spacing must be >= 1.50 um
3672 0 METAL4.SP.1.5: Metal4 to Metal4 spacing must be >= 1.50 um
3677 0 METAL5.SP.1.5: Metal5 to Metal5 spacing must be >= 1.50 um
3682 0 METAL6.SP.1.5: Metal6 to Metal6 spacing must be >= 1.50 um
3687 0 METAL7.SP.1.5: Metal7 to Metal7 spacing must be >= 1.50 um
3692 0 METAL8.SP.1.4: Metal8 to Metal8 spacing must be >= 1.50 um
3697 0 METAL9.SP.1.4: Metal9 to Metal9 spacing must be >= 1.50 um
3702 0 METAL1.SP.1.6: Metal1 to Metal1 spacing must be >= 2.50 um
3707 0 METAL2.SP.1.6: Metal2 to Metal2 spacing must be >= 2.50 um
3712 0 METAL3.SP.1.6: Metal3 to Metal3 spacing must be >= 2.50 um
3717 0 METAL4.SP.1.6: Metal4 to Metal4 spacing must be >= 2.50 um
3722 0 METAL5.SP.1.6: Metal5 to Metal5 spacing must be >= 2.50 um
3727 0 METAL6.SP.1.6: Metal6 to Metal6 spacing must be >= 2.50 um
3732 0 METAL7.SP.1.6: Metal7 to Metal7 spacing must be >= 2.50 um
3737 0 METAL8.SP.1.5: Metal8 to Metal8 spacing must be >= 2.50 um
3742 0 METAL9.SP.1.5: Metal9 to Metal9 spacing must be >= 2.50 um
3744 0 METAL1.L.1: Metal1 non-90 degree segments must be >= 0.18 um
3746 0 METAL2.L.1: Metal2 non-90 degree segments must be >= 0.20 um
3748 0 METAL3.L.1: Metal3 non-90 degree segments must be >= 0.20 um
3750 0 METAL4.L.1: Metal4 non-90 degree segments must be >= 0.20 um
3752 0 METAL5.L.1: Metal5 non-90 degree segments must be >= 0.20 um
3754 0 METAL6.L.1: Metal6 non-90 degree segments must be >= 0.20 um
3756 0 METAL7.L.1: Metal7 non-90 degree segments must be >= 0.20 um
3757 0 METAL1.SP.2: Metal1 to bent Metal1 spacing must be >= 0.16 um
3758 0 METAL1.W.3: Bent Metal1 (45 degree angle) width must be >= 0.14
3759 0 METAL2.SP.2: Metal2 to bent Metal2 spacing must be >= 0.18 um
3760 0 METAL2.W.3: Bent Metal2 (45 degree angle) width must be >= 0.16
3761 0 METAL3.SP.2: Metal3 to bent Metal3 spacing must be >= 0.18 um
3762 0 METAL3.W.3: Bent Metal3 (45 degree angle) width must be >= 0.16
3763 0 METAL4.SP.2: Metal4 to bent Metal4 spacing must be >= 0.18 um
3764 0 METAL4.W.3: Bent Metal4 (45 degree angle) width must be >= 0.16
3765 0 METAL5.SP.2: Metal5 to bent Metal5 spacing must be >= 0.18 um
3766 0 METAL5.W.3: Bent Metal5 (45 degree angle) width must be >= 0.16
3767 0 METAL6.SP.2: Metal6 to bent Metal6 spacing must be >= 0.18 um
3768 0 METAL6.W.3: Bent Metal6 (45 degree angle) width must be >= 0.16
3769 0 METAL7.SP.2: Metal7 to bent Metal7 spacing must be >= 0.18 um
3770 0 METAL7.W.3: Bent Metal7 (45 degree angle) width must be >= 0.16
3771 0 METAL1.A.1: Metal1 area must be >= 0.07 um
3772 0 METAL2.A.1: Metal2 area must be >= 0.08 um
3773 0 METAL3.A.1: Metal3 area must be >= 0.08 um
3774 0 METAL4.A.1: Metal4 area must be >= 0.08 um
3775 0 METAL5.A.1: Metal5 area must be >= 0.08 um
3776 0 METAL6.A.1: Metal6 area must be >= 0.08 um
3777 0 METAL7.A.1: Metal7 area must be >= 0.08 um
3778 0 METAL8.A.1: Metal8 area must be >= 0.2 um
3779 0 METAL9.A.1: Metal9 area must be >= 0.2 um
3781 0 VIA1.W.1: Via1 shapes must be 0.14x0.14 rectangles
3783 0 VIA1.SP.1: Via1 to Via1 spacing must be >= 0.15 um
3789 0 VIA1.SP.2: Via1 to Via1 spacing must be >= 0.20 um
3791 0 VIA2.W.1: Via2 shapes must be 0.14x0.14 rectangles
3793 0 VIA2.SP.1: Via2 to Via2 spacing must be >= 0.15 um
3799 0 VIA2.SP.2: Via2 to Via2 spacing must be >= 0.20 um
3801 0 VIA3.W.1: Via3 shapes must be 0.14x0.14 rectangles
3803 0 VIA3.SP.1: Via3 to Via3 spacing must be >= 0.15 um
3809 0 VIA3.SP.2: Via3 to Via3 spacing must be >= 0.20 um
3811 0 VIA4.W.1: Via4 shapes must be 0.14x0.14 rectangles
3813 0 VIA4.SP.1: Via4 to Via4 spacing must be >= 0.15 um
3819 0 VIA4.SP.2: Via4 to Via4 spacing must be >= 0.20 um
3821 0 VIA5.W.1: Via5 shapes must be 0.14x0.14 rectangles
3823 0 VIA5.SP.1: Via5 to Via5 spacing must be >= 0.15 um
3829 0 VIA5.SP.2: Via5 to Via5 spacing must be >= 0.20 um
3831 0 VIA6.W.1: Via6 shapes must be 0.14x0.14 rectangles
3833 0 VIA6.SP.1: Via6 to Via6 spacing must be >= 0.15 um
3839 0 VIA6.SP.2: Via6 to Via6 spacing must be >= 0.20 um
3841 0 VIA7.W.1: Via7 shapes must be 0.36x0.36 rectangles
3843 0 VIA7.SP.1: Via7 to Via7 spacing must be >= 0.36 um
3845 0 VIA8.W.1: Via8 shapes must be 0.36x0.36 rectangles
3847 0 VIA8.SP.1: Via8 to Via8 spacing must be >= 0.36 um
3848 0 VIA1.E.1: Metal1 to Via1 enclosure must be >= 0.005 um
3850 0 VIA1.E.1: Metal1 to Via1 enclosure must be >= 0.005 um
3854 0 VIA1.E.2: Metal1 to Via1 enclosure on opposite sides must be >= 0.06 um
3855 0 VIA2.E.1: Metal2 to Via2 enclosure must be >= 0.005 um
3857 0 VIA2.E.1: Metal2 to Via2 enclosure must be >= 0.005 um
3861 0 VIA2.E.2: Metal2 to Via2 enclosure on opposite sides must be >= 0.06 um
3862 0 VIA3.E.1: Metal3 to Via3 enclosure must be >= 0.005 um
3864 0 VIA3.E.1: Metal3 to Via3 enclosure must be >= 0.005 um
3868 0 VIA3.E.2: Metal3 to Via3 enclosure on opposite sides must be >= 0.06 um
3869 0 VIA4.E.1: Metal4 to Via4 enclosure must be >= 0.005 um
3871 0 VIA4.E.1: Metal4 to Via4 enclosure must be >= 0.005 um
3875 0 VIA4.E.2: Metal4 to Via4 enclosure on opposite sides must be >= 0.06 um
3876 0 VIA5.E.1: Metal5 to Via5 enclosure must be >= 0.005 um
3878 0 VIA5.E.1: Metal5 to Via5 enclosure must be >= 0.005 um
3882 0 VIA5.E.2: Metal5 to Via5 enclosure on opposite sides must be >= 0.06 um
3883 0 VIA6.E.1: Metal6 to Via6 enclosure must be >= 0.005 um
3885 0 VIA6.E.1: Metal6 to Via6 enclosure must be >= 0.005 um
3889 0 VIA6.E.2: Metal6 to Via6 enclosure on opposite sides must be >= 0.06 um
3890 0 VIA7.E.1: Metal7 to Via7 enclosure must be >= 0.03 um
3892 0 VIA7.E.1: Metal7 to Via7 enclosure must be >= 0.03 um
3896 0 VIA7.E.2: Metal7 to Via7 enclosure on opposite sides must be >= 0.08 um
3897 0 VIA8.E.1: Metal8 to Via8 enclosure must be >= 0.03 um
3899 0 VIA8.E.1: Metal8 to Via8 enclosure must be >= 0.03 um
3903 0 VIA8.E.2: Metal8 to Via8 enclosure on opposite sides must be >= 0.08 um
3904 0 VIA1.X.1: Metal1 must connect to Metal2 with >= 2 Via1 spaced < 0.30 um or >= 4 Via1 spaced < 0.60 um
3905 0 VIA2.X.1: Metal2 must connect to Metal3 with >= 2 Via2 spaced < 0.30 um or >= 4 Via2 spaced < 0.60 um
3906 0 VIA3.X.1: Metal3 must connect to Metal4 with >= 2 Via3 spaced < 0.30 um or >= 4 Via3 spaced < 0.60 um
3907 0 VIA4.X.1: Metal4 must connect to Metal5 with >= 2 Via4 spaced < 0.30 um or >= 4 Via4 spaced < 0.60 um
3908 0 VIA5.X.1: Metal5 must connect to Metal6 with >= 2 Via5 spaced < 0.30 um or >= 4 Via5 spaced < 0.60 um
3909 0 VIA6.X.1: Metal6 must connect to Metal7 with >= 2 Via6 spaced < 0.30 um or >= 4 Via6 spaced < 0.60 um
3910 0 VIA1.X.2: Metal1 must connect to Metal2 with >= 4 Via1 spaced < 0.30 um or >= 9 Via1 spaced < 0.60 um
3911 0 VIA2.X.2: Metal2 must connect to Metal3 with >= 4 Via2 spaced < 0.30 um or >= 9 Via2 spaced < 0.60 um
3912 0 VIA3.X.2: Metal3 must connect to Metal4 with >= 4 Via3 spaced < 0.30 um or >= 9 Via3 spaced < 0.60 um
3913 0 VIA4.X.2: Metal4 must connect to Metal5 with >= 4 Via4 spaced < 0.30 um or >= 9 Via4 spaced < 0.60 um
3914 0 VIA5.X.2: Metal5 must connect to Metal6 with >= 4 Via5 spaced < 0.30 um or >= 9 Via5 spaced < 0.60 um
3915 0 VIA6.X.2: Metal6 must connect to Metal7 with >= 4 Via6 spaced < 0.30 um or >= 9 Via6 spaced < 0.60 um
4182 0 LATCHUP.1: P+SD to NW tap spacing must be <= 25.0 um
4563 0 LATCHUP.2: N+SD to Psub tap spacing must be <= 25.0 um
4566 0 LATCHUP.3: NMOS (I/O or ESD) to PMOS (I/O or ESD) spacing must be >= 18.0 um
4567 0 LATCHUP.3: NMOS (I/O or ESD) to PMOS (I/O or ESD) spacing must be >= 18.0 um
4572 0 LATCHUP.3: NMOS (I/O or ESD) to PMOS (I/O or ESD) spacing must be >= 50.0 um when not blocked by a double guard ring
4576 0 LATCHUP.3: NMOS (I/O or ESD) to PMOS (I/O or ESD) spacing must be >= 50.0 um when not blocked by a double guard ring
4578 0 MSLOT1.W.1_MSLOT1.L.1: Metal1 Slot width/length must be >= 2.0 um
4580 0 MSLOT1.SP.1: Metal1 Slot to Metal1 Slot spacing must be >= 0.12 um
4582 0 MSLOT2.W.1_MSLOT2.L.1: Metal2 Slot width/length must be >= 2.0 um
4584 0 MSLOT2.SP.1: Metal2 Slot to Metal2 Slot spacing must be >= 0.14 um
4586 0 MSLOT3.W.1_MSLOT3.L.1: Metal3 Slot width/length must be >= 2.0 um
4588 0 MSLOT3.SP.1: Metal3 Slot to Metal3 Slot spacing must be >= 0.14 um
4590 0 MSLOT4.W.1_MSLOT4.L.1: Metal4 Slot width/length must be >= 2.0 um
4592 0 MSLOT4.SP.1: Metal4 Slot to Metal4 Slot spacing must be >= 0.14 um
4594 0 MSLOT5.W.1_MSLOT5.L.1: Metal5 Slot width/length must be >= 2.0 um
4596 0 MSLOT5.SP.1: Metal5 Slot to Metal5 Slot spacing must be >= 0.14 um
4598 0 MSLOT6.W.1_MSLOT6.L.1: Metal6 Slot width/length must be >= 2.0 um
4600 0 MSLOT6.SP.1: Metal6 Slot to Metal6 Slot spacing must be >= 0.14 um
4602 0 MSLOT7.W.1_MSLOT7.L.1: Metal7 Slot width/length must be >= 2.0 um
4604 0 MSLOT7.SP.1: Metal7 Slot to Metal7 Slot spacing must be >= 0.14 um
4606 0 MSLOT8.W.1_MSLOT8.L.1: Metal8 Slot width/length must be >= 2.0 um
4608 0 MSLOT8.SP.1: Metal8 Slot to Metal8 Slot spacing must be >= 0.44 um
4610 0 MSLOT9.W.1_MSLOT9.L.1: Metal9 Slot width/length must be >= 2.0 um
4612 0 MSLOT9.SP.1: Metal9 Slot to Metal9 Slot spacing must be >= 0.44 um
4616 0 ESD.1: ESD gate width must be >= 15.0 um and <= 65.0 um
4617 0 ESD.4: N+ source should connect to Pad or Bulk
4618 0 ESD.4: P+ source should connect to Pad or Nwell
4619 0 ESD.5: NMOS I/O and ESD devices must be inside P+ rings
4620 0 ESD.6: PMOS I/O and ESD devices must be inside N+ rings
4621 0 ESD.7: P+ taps can NOT butt NMOS I/O and ESD devices
4622 0 ESD.7: N+ taps can NOT butt PMOS I/O and ESD devices
4623 0 ESD.8: N+ drains must be non-salicided (except Contact area)
4624 0 ESD.8: P+ drains must be non-salicided (except Contact area)
4627 0 ESD.11: SiProt to Poly gate overlap must be >= 0.05 um
4629 0 ESD.12: SiProt to Poly gate enclosure must be >= 1.8 um
4631 0 ESD.13: SiProt to Oxide overlap must be >= 1.8 um
4635 0 ESD.14: ESD gate length must be == 0.3 um
4639 0 ESD.15: Poly gate to Cont spacing must be >= 0.25 um
4640 0 ESD.15: Poly gate to Cont spacing must be >= 0.25 um
4641 0 BONDPAD.O.1: Bondpads must contain Metal 1
4642 0 BONDPAD.O.1: Bondpads must contain Metal 2
4643 0 BONDPAD.O.1: Bondpads must contain Metal 3
4644 0 BONDPAD.O.1: Bondpads must contain Metal 4
4645 0 BONDPAD.O.1: Bondpads must contain Metal 5
4646 0 BONDPAD.O.1: Bondpads must contain Metal 6
4647 0 BONDPAD.O.1: Bondpads must contain Metal 7
4648 0 BONDPAD.O.1: Bondpads must contain Metal 8
4649 0 BONDPAD.O.1: Bondpads must contain Metal 9
4650 0 BONDPAD.O.2: Bondpad Metal1/Metal2 intersection must contain Via 1
4651 0 BONDPAD.O.2: Bondpad Metal2/Metal3 intersection must contain Via 2
4652 0 BONDPAD.O.2: Bondpad Metal3/Metal4 intersection must contain Via 3
4653 0 BONDPAD.O.2: Bondpad Metal4/Metal5 intersection must contain Via 4
4654 0 BONDPAD.O.2: Bondpad Metal5/Metal6 intersection must contain Via 5
4655 0 BONDPAD.O.2: Bondpad Metal6/Metal7 intersection must contain Via 6
4656 0 BONDPAD.O.2: Bondpad Metal7/Metal8 intersection must contain Via 7
4657 0 BONDPAD.O.2: Bondpad Metal8/Metal9 intersection must contain Via 8
4659 0 BONDPAD.E.1: Metal1 to Bondpad enclosure must be >= 2.0 um
4661 0 BONDPAD.E.1: Metal1 to Bondpad enclosure must be >= 2.0 um
4662 0 BONDPAD.SP.2: Bondpad Metal1 to Metal1 spacing must be >= 3.0 um
4664 0 BONDPAD.E.1: Metal2 to Bondpad enclosure must be >= 2.0 um
4666 0 BONDPAD.E.1: Metal2 to Bondpad enclosure must be >= 2.0 um
4667 0 BONDPAD.SP.2: Bondpad Metal2 to Metal2 spacing must be >= 3.0 um
4669 0 BONDPAD.E.1: Metal3 to Bondpad enclosure must be >= 2.0 um
4671 0 BONDPAD.E.1: Metal3 to Bondpad enclosure must be >= 2.0 um
4672 0 BONDPAD.SP.2: Bondpad Metal3 to Metal3 spacing must be >= 3.0 um
4674 0 BONDPAD.E.1: Metal4 to Bondpad enclosure must be >= 2.0 um
4676 0 BONDPAD.E.1: Metal4 to Bondpad enclosure must be >= 2.0 um
4677 0 BONDPAD.SP.2: Bondpad Metal4 to Metal4 spacing must be >= 3.0 um
4679 0 BONDPAD.E.1: Metal5 to Bondpad enclosure must be >= 2.0 um
4681 0 BONDPAD.E.1: Metal5 to Bondpad enclosure must be >= 2.0 um
4682 0 BONDPAD.SP.2: Bondpad Metal5 to Metal5 spacing must be >= 3.0 um
4684 0 BONDPAD.E.1: Metal6 to Bondpad enclosure must be >= 2.0 um
4686 0 BONDPAD.E.1: Metal6 to Bondpad enclosure must be >= 2.0 um
4687 0 BONDPAD.SP.2: Bondpad Metal6 to Metal6 spacing must be >= 3.0 um
4689 0 BONDPAD.E.1: Metal7 to Bondpad enclosure must be >= 2.0 um
4691 0 BONDPAD.E.1: Metal7 to Bondpad enclosure must be >= 2.0 um
4692 0 BONDPAD.SP.2: Bondpad Metal7 to Metal7 spacing must be >= 3.0 um
4694 0 BONDPAD.E.1: Metal8 to Bondpad enclosure must be >= 2.0 um
4696 0 BONDPAD.E.1: Metal8 to Bondpad enclosure must be >= 2.0 um
4697 0 BONDPAD.SP.2: Bondpad Metal8 to Metal8 spacing must be >= 3.0 um
4699 0 BONDPAD.E.1: Metal9 to Bondpad enclosure must be >= 2.0 um
4701 0 BONDPAD.E.1: Metal9 to Bondpad enclosure must be >= 2.0 um
4702 0 BONDPAD.SP.2: Bondpad Metal9 to Metal9 spacing must be >= 3.0 um
4705 0 BONDPAD.W.1: Bondpad width must be >= 52.0 um
4707 0 BONDPAD.W.1: Bondpad width must be >= 52.0 um
4709 0 BONDPAD.SP.1: Bondpad to Bondpad spacing must be >= 8.0 um
4710 0 BONDPAD.L.1: Bondpad length must be >= 68.0 um
4711 0 BONDPAD.B.1: Bondpad Metal1 must have bevelled corners
4712 0 BONDPAD.B.1: Bondpad Metal2 must have bevelled corners
4713 0 BONDPAD.B.1: Bondpad Metal3 must have bevelled corners
4714 0 BONDPAD.B.1: Bondpad Metal4 must have bevelled corners
4715 0 BONDPAD.B.1: Bondpad Metal5 must have bevelled corners
4716 0 BONDPAD.B.1: Bondpad Metal6 must have bevelled corners
4717 0 BONDPAD.B.1: Bondpad Metal7 must have bevelled corners
4718 0 BONDPAD.B.1: Bondpad Metal8 must have bevelled corners
4719 0 BONDPAD.B.1: Bondpad Metal9 must have bevelled corners
4721 0 BONDPAD.B.1: Bondpad Metal1 beveled segments must be >= 1.8 um and <= 3.2 um
4723 0 BONDPAD.B.1: Bondpad Metal2 beveled segments must be >= 1.8 um and <= 3.2 um
4725 0 BONDPAD.B.1: Bondpad Metal3 beveled segments must be >= 1.8 um and <= 3.2 um
4727 0 BONDPAD.B.1: Bondpad Metal4 beveled segments must be >= 1.8 um and <= 3.2 um
4729 0 BONDPAD.B.1: Bondpad Metal5 beveled segments must be >= 1.8 um and <= 3.2 um
4731 0 BONDPAD.B.1: Bondpad Metal6 beveled segments must be >= 1.8 um and <= 3.2 um
4733 0 BONDPAD.B.1: Bondpad Metal7 beveled segments must be >= 1.8 um and <= 3.2 um
4735 0 BONDPAD.B.1: Bondpad Metal8 beveled segments must be >= 1.8 um and <= 3.2 um
4737 0 BONDPAD.B.1: Bondpad Metal9 beveled segments must be >= 1.8 um and <= 3.2 um
4740 0 BONDPAD.SP.3: Bondpad Via1 to Bondpad Via1 spacing must be >= 0.22 um
4743 0 BONDPAD.SP.3: Bondpad Via2 to Bondpad Via2 spacing must be >= 0.22 um
4746 0 BONDPAD.SP.3: Bondpad Via3 to Bondpad Via3 spacing must be >= 0.22 um
4749 0 BONDPAD.SP.3: Bondpad Via4 to Bondpad Via4 spacing must be >= 0.22 um
4752 0 BONDPAD.SP.3: Bondpad Via5 to Bondpad Via5 spacing must be >= 0.22 um
4755 0 BONDPAD.SP.3: Bondpad Via6 to Bondpad Via6 spacing must be >= 0.22 um
4758 0 BONDPAD.SP.4: Bondpad Via7 to Bondpad Via7 spacing must be >= 0.54 um
4761 0 BONDPAD.SP.4: Bondpad Via8 to Bondpad Via8 spacing must be >= 0.54 um
4763 0 BONDPAD.E.2: Bondpad Metal1 to Via1 enclosure must be >= 0.05 um
4765 0 BONDPAD.E.2: Bondpad Metal1 to Via1 enclosure must be >= 0.05 um
4767 0 BONDPAD.E.2: Bondpad Metal2 to Via2 enclosure must be >= 0.05 um
4769 0 BONDPAD.E.2: Bondpad Metal2 to Via2 enclosure must be >= 0.05 um
4771 0 BONDPAD.E.2: Bondpad Metal3 to Via3 enclosure must be >= 0.05 um
4773 0 BONDPAD.E.2: Bondpad Metal3 to Via3 enclosure must be >= 0.05 um
4775 0 BONDPAD.E.2: Bondpad Metal4 to Via4 enclosure must be >= 0.05 um
4777 0 BONDPAD.E.2: Bondpad Metal4 to Via4 enclosure must be >= 0.05 um
4779 0 BONDPAD.E.2: Bondpad Metal5 to Via5 enclosure must be >= 0.05 um
4781 0 BONDPAD.E.2: Bondpad Metal5 to Via5 enclosure must be >= 0.05 um
4783 0 BONDPAD.E.2: Bondpad Metal6 to Via6 enclosure must be >= 0.05 um
4785 0 BONDPAD.E.2: Bondpad Metal6 to Via6 enclosure must be >= 0.05 um
4787 0 BONDPAD.E.3: Bondpad Metal7 to Via7 enclosure must be >= 0.09 um
4789 0 BONDPAD.E.3: Bondpad Metal7 to Via7 enclosure must be >= 0.09 um
4791 0 BONDPAD.E.3: Bondpad Metal8 to Via8 enclosure must be >= 0.09 um
4793 0 BONDPAD.E.3: Bondpad Metal8 to Via8 enclosure must be >= 0.09 um
4795 0 BONDPAD.E.2: Bondpad Metal2 to Via1 enclosure must be >= 0.05 um
4797 0 BONDPAD.E.2: Bondpad Metal2 to Via1 enclosure must be >= 0.05 um
4799 0 BONDPAD.E.2: Bondpad Metal3 to Via2 enclosure must be >= 0.05 um
4801 0 BONDPAD.E.2: Bondpad Metal3 to Via2 enclosure must be >= 0.05 um
4803 0 BONDPAD.E.2: Bondpad Metal4 to Via3 enclosure must be >= 0.05 um
4805 0 BONDPAD.E.2: Bondpad Metal4 to Via3 enclosure must be >= 0.05 um
4807 0 BONDPAD.E.2: Bondpad Metal5 to Via4 enclosure must be >= 0.05 um
4809 0 BONDPAD.E.2: Bondpad Metal5 to Via4 enclosure must be >= 0.05 um
4811 0 BONDPAD.E.2: Bondpad Metal6 to Via5 enclosure must be >= 0.05 um
4813 0 BONDPAD.E.2: Bondpad Metal6 to Via5 enclosure must be >= 0.05 um
4815 0 BONDPAD.E.2: Bondpad Metal7 to Via6 enclosure must be >= 0.05 um
4817 0 BONDPAD.E.2: Bondpad Metal7 to Via6 enclosure must be >= 0.05 um
4819 0 BONDPAD.E.3: Bondpad Metal8 to Via7 enclosure must be >= 0.09 um
4821 0 BONDPAD.E.3: Bondpad Metal8 to Via7 enclosure must be >= 0.09 um
4823 0 BONDPAD.E.3: Bondpad Metal9 to Via8 enclosure must be >= 0.09 um
4825 0 BONDPAD.E.3: Bondpad Metal9 to Via8 enclosure must be >= 0.09 um
4826 0 BONDPAD.R.1: Minimum Bondpad Via1 inside Metal1 to Metal2 crossing must be >= 16.0
4827 0 BONDPAD.R.1: Minimum Bondpad Via2 inside Metal2 to Metal3 crossing must be >= 16.0
4828 0 BONDPAD.R.1: Minimum Bondpad Via3 inside Metal3 to Metal4 crossing must be >= 16.0
4829 0 BONDPAD.R.1: Minimum Bondpad Via4 inside Metal4 to Metal5 crossing must be >= 16.0
4830 0 BONDPAD.R.1: Minimum Bondpad Via5 inside Metal5 to Metal6 crossing must be >= 16.0
4831 0 BONDPAD.R.1: Minimum Bondpad Via6 inside Metal6 to Metal7 crossing must be >= 16.0
4832 0 BONDPAD.R.2: Minimum Bondpad Via7 inside Metal7 to Metal8 crossing must be >= 4.0
4833 0 BONDPAD.R.2: Minimum Bondpad Via8 inside Metal8 to Metal9 crossing must be >= 4.0
4835 0 BONDPAD.SP.5: Bondpad Metal1 slot to Bondpad Metal1 slot spacing must be == 1.50
4837 0 BONDPAD.SP.5: Bondpad Metal2 slot to Bondpad Metal2 slot spacing must be == 1.50
4839 0 BONDPAD.SP.5: Bondpad Metal3 slot to Bondpad Metal3 slot spacing must be == 1.50
4841 0 BONDPAD.SP.5: Bondpad Metal4 slot to Bondpad Metal4 slot spacing must be == 1.50
4843 0 BONDPAD.SP.5: Bondpad Metal5 slot to Bondpad Metal5 slot spacing must be == 1.50
4845 0 BONDPAD.SP.5: Bondpad Metal6 slot to Bondpad Metal6 slot spacing must be == 1.50
4847 0 BONDPAD.SP.5: Bondpad Metal7 slot to Bondpad Metal7 slot spacing must be == 1.50
4849 0 BONDPAD.SP.5: Bondpad Metal8 slot to Bondpad Metal8 slot spacing must be == 1.50
4850 0 BONDPAD.W.4: Bondpad Metal1 slot width must be == 1.00
4851 0 BONDPAD.W.4: Bondpad Metal2 slot width must be == 1.00
4852 0 BONDPAD.W.4: Bondpad Metal3 slot width must be == 1.00
4853 0 BONDPAD.W.4: Bondpad Metal4 slot width must be == 1.00
4854 0 BONDPAD.W.4: Bondpad Metal5 slot width must be == 1.00
4855 0 BONDPAD.W.4: Bondpad Metal6 slot width must be == 1.00
4856 0 BONDPAD.W.4: Bondpad Metal7 slot width must be == 1.00
4857 0 BONDPAD.W.4: Bondpad Metal8 slot width must be == 1.00
4858 0 BONDPAD.W.5: Bondpad Metal1 outside Metal1 ring width must be == 5.00
4859 0 BONDPAD.W.5: Bondpad Metal2 outside Metal2 ring width must be == 5.00
4860 0 BONDPAD.W.5: Bondpad Metal3 outside Metal3 ring width must be == 5.00
4861 0 BONDPAD.W.5: Bondpad Metal4 outside Metal4 ring width must be == 5.00
4862 0 BONDPAD.W.5: Bondpad Metal5 outside Metal5 ring width must be == 5.00
4863 0 BONDPAD.W.5: Bondpad Metal6 outside Metal6 ring width must be == 5.00
4864 0 BONDPAD.W.5: Bondpad Metal7 outside Metal7 ring width must be == 5.00
4865 0 BONDPAD.W.5: Bondpad Metal8 outside Metal8 ring width must be == 5.00
4866 0 BONDPAD.SP.6: Bondpad Metal1 to Bondpad Metal1 spacing across first slot must be >= 1.00 um and <= 3.50 um
4867 0 BONDPAD.SP.6: Bondpad Metal1 to Bondpad Metal1 spacing across first slot must be >= 1.00 um and <= 3.50 um
4868 0 BONDPAD.SP.6: Bondpad Metal2 to Bondpad Metal2 spacing across first slot must be >= 1.00 um and <= 3.50 um
4869 0 BONDPAD.SP.6: Bondpad Metal2 to Bondpad Metal2 spacing across first slot must be >= 1.00 um and <= 3.50 um
4870 0 BONDPAD.SP.6: Bondpad Metal3 to Bondpad Metal3 spacing across first slot must be >= 1.00 um and <= 3.50 um
4871 0 BONDPAD.SP.6: Bondpad Metal3 to Bondpad Metal3 spacing across first slot must be >= 1.00 um and <= 3.50 um
4872 0 BONDPAD.SP.6: Bondpad Metal4 to Bondpad Metal4 spacing across first slot must be >= 1.00 um and <= 3.50 um
4873 0 BONDPAD.SP.6: Bondpad Metal4 to Bondpad Metal4 spacing across first slot must be >= 1.00 um and <= 3.50 um
4874 0 BONDPAD.SP.6: Bondpad Metal5 to Bondpad Metal5 spacing across first slot must be >= 1.00 um and <= 3.50 um
4875 0 BONDPAD.SP.6: Bondpad Metal5 to Bondpad Metal5 spacing across first slot must be >= 1.00 um and <= 3.50 um
4876 0 BONDPAD.SP.6: Bondpad Metal6 to Bondpad Metal6 spacing across first slot must be >= 1.00 um and <= 3.50 um
4877 0 BONDPAD.SP.6: Bondpad Metal6 to Bondpad Metal6 spacing across first slot must be >= 1.00 um and <= 3.50 um
4878 0 BONDPAD.SP.6: Bondpad Metal7 to Bondpad Metal7 spacing across first slot must be >= 1.00 um and <= 3.50 um
4879 0 BONDPAD.SP.6: Bondpad Metal7 to Bondpad Metal7 spacing across first slot must be >= 1.00 um and <= 3.50 um
4880 0 BONDPAD.SP.6: Bondpad Metal8 to Bondpad Metal8 spacing across first slot must be >= 1.00 um and <= 3.50 um
4881 0 BONDPAD.SP.6: Bondpad Metal8 to Bondpad Metal8 spacing across first slot must be >= 1.00 um and <= 3.50 um
4883 0 BONDPAD.SP.7: Bondpad Via1 array to Bondpad Via1 array spacing must be >= 1.1 um
4885 0 BONDPAD.SP.7: Bondpad Via2 array to Bondpad Via2 array spacing must be >= 1.1 um
4887 0 BONDPAD.SP.7: Bondpad Via3 array to Bondpad Via3 array spacing must be >= 1.1 um
4889 0 BONDPAD.SP.7: Bondpad Via4 array to Bondpad Via4 array spacing must be >= 1.1 um
4891 0 BONDPAD.SP.7: Bondpad Via5 array to Bondpad Via5 array spacing must be >= 1.1 um
4893 0 BONDPAD.SP.7: Bondpad Via6 array to Bondpad Via6 array spacing must be >= 1.1 um
4895 0 BONDPAD.SP.7: Bondpad Via7 array to Bondpad Via7 array spacing must be >= 1.1 um
4897 0 BONDPAD.SP.7: Bondpad Via8 array to Bondpad Via8 array spacing must be >= 1.1 um
4900 0 OXIDER.W.1.1: Oxide resistor width must be >= 0.2 um
4903 0 POLYR.W.1.1: Poly resistor width must be >= 0.2 um
